# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  tags:
    - '*'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    ‐ name: build-push
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        registry: daocloud.io
        repository: daozzg/alertcenter-wechat
        tag_with_ref: true

    # Runs a set of commands using the runners shell
    - name: run on gce
      run: |
        echo todo
        echo test, and deploy your project.
